[project]
name = "mcp-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.21.0",
    "openai>=1.51.0",
    "pydantic>=2.9.2",
    "rich>=13.9.2",
    "ruff>=0.14.4",
]
